---

- name: Configuring log file rotation
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/postgresql-common
    owner: root
    group: root
    mode: "0644"
  with_first_found:
    - "host_files/{{ inventory_hostname }}/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "host_files/{{ inventory_hostname }}/logrotate_postgresql-common.j2"
    - "group_files/servers-production/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/logrotate_postgresql-common.j2"
    - "group_files/servers-development/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/logrotate_postgresql-common.j2"
    - "group_files/servers-demo/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/logrotate_postgresql-common.j2"
    - "group_files/servers/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/logrotate_postgresql-common.j2"
    - "logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_postgresql-common.j2"
  when: hm_pgsql__logrotate

- name: Configuring Nagios monitoring
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/postgresql.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "host_files/{{ inventory_hostname }}/nrpe_postgresql.cfg.j2"
    - "group_files/servers-production/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/nrpe_postgresql.cfg.j2"
    - "group_files/servers-development/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/nrpe_postgresql.cfg.j2"
    - "group_files/servers-demo/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/nrpe_postgresql.cfg.j2"
    - "group_files/servers/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/nrpe_postgresql.cfg.j2"
    - "nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe_postgresql.cfg.j2"
  notify: Restart NRPE service
  when: '"servers-monitored" in group_names'

- name: Configuring system status script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status.d/20-postgresql
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "host_files/{{ inventory_hostname }}/system-status-postgresql.j2"
    - "group_files/servers-production/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/system-status-postgresql.j2"
    - "group_files/servers-development/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/system-status-postgresql.j2"
    - "group_files/servers-demo/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/system-status-postgresql.j2"
    - "group_files/servers/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/system-status-postgresql.j2"
    - "system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "system-status-postgresql.j2"
  when: '"servers-commonenv" in group_names'

- name: Ensuring PostgreSQL service is running and enabled at system start
  service:
    name: "{{ hm_pgsql__service_name }}"
    state: started
    enabled: yes
