---

- name: Configuring log file rotation
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/postgresql-common
    owner: root
    group: root
    mode: "0644"
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.postgresql/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.postgresql/logrotate_postgresql-common.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/logrotate_postgresql-common.j2"
    - "inventory/group_files/servers/honzamach.postgresql/logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.postgresql/logrotate_postgresql-common.j2"
    - "logrotate_postgresql-common.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_postgresql-common.j2"
  when: hm_pgsql__logrotate

- name: Configuring Nagios monitoring
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/postgresql.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.postgresql/nrpe_postgresql.cfg.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/nrpe_postgresql.cfg.j2"
    - "inventory/group_files/servers/honzamach.postgresql/nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.postgresql/nrpe_postgresql.cfg.j2"
    - "nrpe_postgresql.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe_postgresql.cfg.j2"
  notify: Restart NRPE service
  when: '"servers_monitored" in group_names'

- name: Configuring system status script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status.d/20-postgresql
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.postgresql/system-status-postgresql.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.postgresql/system-status-postgresql.j2"
    - "inventory/group_files/servers/honzamach.postgresql/system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.postgresql/system-status-postgresql.j2"
    - "system-status-postgresql.{{ ansible_lsb['codename'] }}.j2"
    - "system-status-postgresql.j2"
  when: '"servers_monitored" in group_names'

- name: Ensuring PostgreSQL service is running and enabled at system start
  service:
    name: "{{ hm_pgsql__service_name }}"
    state: started
    enabled: yes
