---

- name: Installing APT repository GPG key for PostgreSQL database
  apt_key:
    url: "{{ hm_pgsql__apt_key_url }}"
    id: "{{ hm_pgsql__apt_key_id }}"
    state: present

- name: Installing APT repository list file for PostgreSQL database
  apt_repository:
    repo: "{{ hm_pgsql__apt_repository }}"
    state: present
    filename: pgsql
    update_cache: yes

- name: Removing PostgreSQL related packages
  apt:
    name: "{{ hm_pgsql__remove_list }}"
    state: absent
  when: hm_pgsql__apt_remove_previous

- name: Installing PostgreSQL related packages
  apt:
    name: "{{ hm_pgsql__package_list }}"
    state: latest
    update_cache: "{{ hm_pgsql__apt_force_update }}"
