---

- name: Restart PostgreSQL service
  service:
    name: "{{ hm_pgsql__service_name }}"
    state: restarted

- name: Restart NRPE service
  service:
    name: "{{ hm_monitored__service_name }}"
    state: restarted
